deployment:
  tasks:
    - export NVM_DIR="$HOME/.nvm"
    - source $NVM_DIR/nvm.sh
    - nvm use 18
    - npm install
    - npm run generate
    - rm -rf public_html/grupoforpa.codersti.com/*
    - cp -r dist/* public_html/grupoforpa.codersti.com/
